var getskins = [{
	"skin:skip": "VSG",
	"vsg-skins:skip": "vsg",
	".vjs-control-bar[font-size]:px": "14",
	".vjs-control-bar2[background-color]": "#000000",
	".vjs-control-bar[background-color]:important": "rgba(0,0,0,0.3)",
	".vjs-play-progress| .vjs-volume-level[background-color]": "#2483d5",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-big-play-button[background-color]": "rgba(0,0,0,0.45)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "rgba(36,131,213,0.9)",
	".vjs-big-play-button[border-radius]:percent": "50",
	".vjs-big-play-button[font-size]:em": "3.5",
	".vjs-big-play-button[height]:emimportant": "2",
	".vjs-big-play-button[line-height]:emimportant": "2",
	".vjs-big-play-button[margin-top]:emimportant": "-1",
	"radius:skip": "2",
	".vjs-loading-spinner[border-color]": "rgba(36,131,213,0.8)",
	"customcss:skip": ""
}, {
	"skin:skip": "Sublim",
	"vsg-skins:skip": "default",
	".vjs-control-bar2[background-color]": "transparent",
	".vjs-control-bar[background-color]:important": "rgba(0,0,0,0)",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-play-progress| .vjs-volume-level[background-color]": "#cccccc",
	".vjs-control-bar[font-size]:px": "18",
	".vjs-big-play-button[background-color]": "rgba(255,255,255,0.25)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "rgba(255,255,255,0.45)",
	".vjs-big-play-button[font-size]:em": "3.5",
	".vjs-big-play-button[border-radius]:percent": "35",
	".vjs-big-play-button[height]:emimportant": "1.6",
	".vjs-big-play-button[line-height]:emimportant": "1.6",
	".vjs-big-play-button[margin-top]:emimportant": "-0.8",
	"radius:skip": "1.6",
	".vjs-loading-spinner[border-color]": "rgba(255,255,255,0.7)",
	"customcss:skip": ".video-js  .vjs-progress-holder {\r\n    font-size: 1.7em;\r\nborder-radius: 10px;\r\n}\r\n.video-js .vjs-progress-holder .vjs-play-progress, .video-js .vjs-progress-holder .vjs-load-progress, .video-js .vjs-progress-holder .vjs-load-progress div, .video-js .vjs-slider,.vjs-volume-level {\r\n    border-radius: 10px;\r\n}\r\n.video-js .vjs-load-progress {\r\n    background: rgba(255,255,255,0.2);\r\n}"
}, {
	"skin:skip": "Magnified",
	"vsg-skins:skip": "vsg",
	".vjs-control-bar[font-size]:px": "16",
	".vjs-control-bar2[background-color]": "#fcfcfc",
	".vjs-control-bar[background-color]:important": "rgba(252,252,252,0.19)",
	".vjs-play-progress| .vjs-volume-level[background-color]": "#cccccc",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-big-play-button[background-color]": "rgba(255,255,255,0.1)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "rgba(255,255,255,0.23)",
	".vjs-big-play-button[border-radius]:percent": "50",
	".vjs-big-play-button[font-size]:em": "6",
	".vjs-big-play-button[height]:emimportant": "2",
	".vjs-big-play-button[line-height]:emimportant": "2",
	".vjs-big-play-button[margin-top]:emimportant": "-1",
	"radius:skip": "2",
	".vjs-loading-spinner[border-color]": "rgba(255,255,255,0.7)",
	"customcss:skip": ""
}, {
	"skin:skip": "SunRise",
	"vsg-skins:skip": "vsg",
	".vjs-control-bar[font-size]:px": "14",
	".vjs-control-bar2[background-color]": "#ebff04",
	".vjs-control-bar[background-color]:important": "rgba(235,255,4,0.4)",
	".vjs-play-progress| .vjs-volume-level[background-color]": "#cccccc",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-big-play-button[background-color]": "rgba(235,255,4,0.4)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "rgba(235,255,4,0.5)",
	".vjs-big-play-button[border-radius]:percent": "50",
	".vjs-big-play-button[font-size]:em": "4",
	".vjs-big-play-button[height]:emimportant": "2",
	".vjs-big-play-button[line-height]:emimportant": "2",
	".vjs-big-play-button[margin-top]:emimportant": "-1",
	"radius:skip": "2",
	".vjs-loading-spinner[border-color]": "rgba(255,255,255,0.7)",
	"customcss:skip": ""
}, {
	"skin:skip": "TechSkin",
	"vsg-skins:skip": "vsg",
	".vjs-control-bar[font-size]:px": "14",
	".vjs-control-bar2[background-color]": "#0e223d",
	".vjs-control-bar[background-color]:important": "#0e223d",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-play-progress| .vjs-volume-level[background-color]": "rgba(14,34,61,0.8)",
	".vjs-big-play-button[background-color]": "rgba(14,34,61,0.7)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "#0e223d",
	".vjs-big-play-button[border-radius]:percent": "12",
	".vjs-big-play-button[font-size]:em": "3.5",
	".vjs-big-play-button[height]:emimportant": "1.4",
	".vjs-big-play-button[line-height]:emimportant": "1.4",
	".vjs-big-play-button[margin-top]:emimportant": "-0.7",
	"radius:skip": "1.4",
	".vjs-loading-spinner[border-color]": "rgba(14,34,61,0.84)",
	"customcss:skip": ""
}, {
	"skin:skip": "Youtube",
	"vsg-skins:skip": "vsg",
	".vjs-control-bar[font-size]:px": "12",
	".vjs-control-bar2[background-color]": "#000000",
	".vjs-control-bar[background-color]:important": "rgba(0,0,0,0.3)",
	".vjs-play-progress| .vjs-volume-level[background-color]": "#cc181e",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-big-play-button[background-color]": "rgba(0,0,0,0.5)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "#cc181e",
	".vjs-big-play-button[border-radius]:percent": "20",
	".vjs-big-play-button[font-size]:em": "2.5",
	".vjs-big-play-button[height]:emimportant": "1.4",
	".vjs-big-play-button[line-height]:emimportant": "1.4",
	".vjs-big-play-button[margin-top]:emimportant": "-0.7",
	"radius:skip": "1.4",
	".vjs-loading-spinner[border-color]": "#cc181e",
	"customcss:skip": ".video-js .vjs-load-progress {\r\n    background: rgba(255,255,255,0.3);\r\n}"
}, {
	"skin:skip": "Facebook Player",
	"vsg-skins:skip": "default",
	".vjs-control-bar[font-size]:px": "18",
	".vjs-control-bar2[background-color]": "transparent",
	".vjs-control-bar[background-color]:important": "rgba(0,0,0,0)",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-play-progress| .vjs-volume-level[background-color]": "#2483d5",
	".vjs-big-play-button[background-color]": "rgba(0,0,0,0.35)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "rgba(0,0,0,0.35)",
	".vjs-big-play-button[border-radius]:percent": "50",
	".vjs-big-play-button[font-size]:em": "3.5",
	".vjs-big-play-button[height]:emimportant": "2",
	".vjs-big-play-button[line-height]:emimportant": "2",
	".vjs-big-play-button[margin-top]:emimportant": "-1",
	"radius:skip": "2",
	".vjs-loading-spinner[border-color]": "rgba(255,255,255,0.7)",
	"customcss:skip": ".video-js .vjs-big-play-button {\r\n    height: 2em !important;\r\n    width: 2em !important;\r\n    line-height: 1.9em !important;\r\n    margin-top: -1em !important;\r\nmargin-left: -1em;\r\nborder-width:3px\r\n}\r\n .video-js .vjs-icon-play:before, .video-js .vjs-big-play-button:before {\r\n    font-size: 50px;\r\n}\r\n.video-js  .vjs-progress-holder {\r\n    font-size: 1.7em;\r\nborder-radius: 10px;\r\n}\r\n.video-js .vjs-progress-holder .vjs-play-progress, .video-js .vjs-progress-holder .vjs-load-progress, .video-js .vjs-progress-holder .vjs-load-progress div, .video-js .vjs-slider,.vjs-volume-level {\r\n    border-radius: 10px;\r\n}\r\n.video-js .vjs-load-progress {\r\n    background: rgba(255,255,255,0.5);\r\n}"
}, {
	"skin:skip": "Twitter",
	"vsg-skins:skip": "default",
	".vjs-control-bar2[background-color]": "transparent",
	".vjs-control-bar[background-color]:important": "rgba(0,0,0,0)",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-play-progress| .vjs-volume-level[background-color]": "#2c97de",
	".vjs-control-bar[font-size]:px": "17",
	".vjs-big-play-button[background-color]": "rgba(44,151,222,0.8)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "rgba(44,151,222,0.9)",
	".vjs-big-play-button[font-size]:em": "2.5",
	".vjs-big-play-button[border-radius]:percent": "50",
	".vjs-big-play-button[height]:emimportant": "2",
	".vjs-big-play-button[line-height]:emimportant": "2",
	".vjs-big-play-button[margin-top]:emimportant": "-1",
	"radius:skip": "2",
	".vjs-loading-spinner[border-color]": "#2c97de",
	"customcss:skip": ".video-js .vjs-big-play-button {\r\n    height: 2em !important;\r\n    width: 2em !important;\r\n    line-height: 1.7em !important;\r\n    margin-top: -1em !important;\r\nmargin-left: -1em;\r\nborder-width:4px\r\n}\r\n .video-js .vjs-icon-play:before, .video-js .vjs-big-play-button:before {\r\n    font-size: 40px;\r\n}\r\n.video-js  .vjs-progress-holder {\r\n    font-size: 1.7em;\r\nborder-radius: 10px;\r\n}\r\n.video-js .vjs-progress-holder .vjs-play-progress, .video-js .vjs-progress-holder .vjs-load-progress, .video-js .vjs-progress-holder .vjs-load-progress div, .video-js .vjs-slider,.vjs-volume-level {\r\n    border-radius: 10px;\r\n}\r\n.video-js .vjs-load-progress {\r\n    background: rgba(255,255,255,0.5);\r\n}\r\n.video-js, .video-js video, .vjs-poster, .video-js .vjs-tech {\r\n    border-radius: 8px;\r\n}"
}, {
	"skin:skip": "Rotten Tomatoes",
	"vsg-skins:skip": "default",
	".vjs-control-bar[font-size]:px": "11",
	".vjs-control-bar2[background-color]": "#3a9425",
	".vjs-control-bar[background-color]:important": "#3a9425",
	".vjs-play-progress| .vjs-volume-level[background-color]": "#f3ec1a",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-big-play-button[background-color]": "rgba(58,148,37,0.7)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "#3a9425",
	".vjs-big-play-button[border-radius]:percent": "15",
	".vjs-big-play-button[font-size]:em": "3",
	".vjs-big-play-button[height]:emimportant": "1.8",
	".vjs-big-play-button[line-height]:emimportant": "1.8",
	".vjs-big-play-button[margin-top]:emimportant": "-0.9",
	"radius:skip": "1.8",
	".vjs-loading-spinner[border-color]": "#3a9425",
	"customcss:skip": ".video-js .vjs-slider {\r\n    background-color: #3b3d41\r\n}\r\n.video-js .vjs-load-progress {\r\n    background: rgba(252,249,133,0.7);\r\n}\r\n.video-js .vjs-big-play-button {\r\n    color: #f3ec1a;\r\n    border-color: #f3ec1a;\r\n}"
}, {
	"skin:skip": "twitch.tv",
	"vsg-skins:skip": "vsg",
	".vjs-control-bar[font-size]:px": "12",
	".vjs-control-bar2[background-color]": "#000000",
	".vjs-control-bar[background-color]:important": "rgba(0,0,0,0.4)",
	".vjs-control-bar[color]": "#ffffff",
	".vjs-play-progress| .vjs-volume-level[background-color]": "#b99beb",
	".vjs-big-play-button[background-color]": "rgba(0,0,0,0)",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "rgba(0,0,0,0)",
	".vjs-big-play-button[border-radius]:percent": "0",
	".vjs-big-play-button[font-size]:em": "8",
	".vjs-big-play-button[height]:emimportant": "1",
	".vjs-big-play-button[line-height]:emimportant": "1",
	".vjs-big-play-button[margin-top]:emimportant": "-0.5",
	"radius:skip": "1",
	".vjs-loading-spinner[border-color]": "#b99beb",
	"customcss:skip": ".video-js .vjs-load-progress {\r\n    background: rgba(255,255,255,0.8);\r\n}\r\n.video-js .vjs-big-play-button:hover{\r\n    color: #b99beb ;\r\n}\r\n.video-js .vjs-control:focus:before, .video-js .vjs-control:hover:before {\r\n   color: #b99beb ;\r\n   text-shadow:none\r\n}"
}, {
	"skin:skip": "Reset",
	"vsg-skins:skip": "default",
	".vjs-control-bar2[background-color]": "#000000",
	".vjs-control-bar[background-color]:important": "",
	".vjs-control-bar[color]": "",
	".vjs-play-progress| .vjs-volume-level[background-color]": "",
	".vjs-control-bar[font-size]:px": "10",
	".vjs-big-play-button[background-color]": "",
	"@hover .vjs-big-play-button|.vjs-big-play-button@focus|.vjs-big-play-button@active[background-color]": "",
	".vjs-big-play-button[font-size]:em": "3",
	".vjs-big-play-button[border-radius]:percent": "12",
	".vjs-big-play-button[height]:emimportant": "1.7",
	".vjs-big-play-button[line-height]:emimportant": "1.7",
	".vjs-big-play-button[margin-top]:emimportant": "-0.85",
	"radius:skip": "1.7",
	".vjs-loading-spinner[border-color]": "",
	"customcss:skip": ""
}];